# Generated by Django 6.0.2 on 2026-02-20 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0004_event_participants_project_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('summary', models.CharField(help_text='Short 1-2 sentence summary', max_length=300)),
                ('content', models.TextField(help_text='Full article content')),
                ('category', models.CharField(choices=[('technical', 'Technical Article'), ('event_recap', 'Event Recap'), ('member_achievement', 'Member Achievement')], default='technical', max_length=20)),
                ('cover_image', models.ImageField(blank=True, help_text='Optional cover image', null=True, upload_to='blog_images/')),
                ('is_published', models.BooleanField(default=False, help_text='Only published articles appear on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(blank=True, help_text='Optional: Link to a club', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
