# Generated by Django 6.0.2 on 2026-02-21 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_event_participants_project_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Django Beginner Notes, Computer Graphics PDF', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_link', models.URLField(help_text='Link to Google Drive, GitHub, etc.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='clubs.club')),
            ],
        ),
    ]
