# Generated by Django 6.0.2 on 2026-02-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='club',
        ),
    ]
